[package]
name = "liquidroute-geyser-plugin"
version = "0.1.0"
edition = "2021"
description = "LiquidRoute Geyser Plugin for DEX aggregation"
authors = ["LiquidRoute Team <info@liquidroute.com>"]
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "config-check"

[dependencies]
agave-geyser-plugin-interface = "~2.1.17"
anyhow = "1.0.75"
bincode = "1.3.3"
bs58 = "0.5.0"
clap = { version = "4.4.11", features = ["derive"] }
crossbeam-channel = "0.5.8"
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros", "fs"] }

[build-dependencies]
anyhow = "1.0.75"